name: Run Bot

on:
  schedule:
    - cron: '0 * * * *' # اجرای خودکار در هر ساعت
  workflow_dispatch: # اجازه اجرای دستی در گیت‌هاب

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          # نصب کتابخانه‌های لازم برای مرورگر و دور زدن ربات
          pip install playwright playwright-stealth
          playwright install chromium

      - name: Run bot script
        run: python bot.py
